spring.application.name=OrderManagement



server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/OrderManagement
spring.datasource.username=postgres
spring.datasource.password=Pawan@123

spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true








